import img_lasanha from '../img/lasanha.png';
import img_strogonoff from '../img/strogonoff.png';
import img_pave from '../img/pave.png';
import img_coxinha from '../img/coxinha.png';
import img_cookie from '../img/cookies.png';
import img_hamburguer from '../img/hamburguer.png';

const especiais = [
    {
        id: '1',
        nome: 'Lasanha Bolonhesa',
        img: img_lasanha,
        nota: '5.0',
        tempo: '50min',
        dificuldade: 'Médio',
        preparo: { 
            sections: [
            {
              title: 'Modo de Preparo',
              data: [
                '1 - MASSA: Cozinhe a massa segundo as orientações do fabricante, despeje em um refratário com água gelada para não grudar e reserve.',
                '',
                '2 - MOLHO A BOLONHESA: Refogue o alho, a cebola, a carne moída, o molho de tomate, deixe cozinhar por 3 minutos e reserve.',
                '',
                '3 - MOLHO BRANCO: Derreta a margarina, coloque as 3 colheres de farinha de trigo e mexa.',
                '',
                '4 - Despeje o leite aos poucos e continue mexendo.',
                '',
                '5 - Por último, coloque o creme de leite, mexa por 1 minuto e desligue o fogo.',
                '',
                '6 - Despeje uma parte do molho à bolonhesa em um refratário, a metade da massa, a metade do presunto, a metade da mussarela, todo o molho branco e o restante da massa.',
                '',
                '7 - Repita as camadas até a borda do recipiente.',
                '',
                '8 - Finalize com o queijo ralado e leve ao forno alto (220° C), preaquecido, por cerca de 20 minutos.',
              ],
            },
            ],
        },
        ingredientes: { sections: [
            {
              title: 'Ingredientes (15 porções)',
              data: ['• 500 g de massa de lasanha',
              '• 500 g de carne moída',
              '• 2 caixas de creme de leite',
              '• 3 colheres de manteiga',
              '• 3 colheres de farinha de trigo',
              '• 500 g de presunto',
              '• 500 g de mussarela',
              '• sal a gosto',
              '• 2 copos de leite',
              '• 1 cebola ralada',
              '• 3 colheres de óleo',
              '• 1 caixa de molho de tomate',
              '• 3 dentes de alho amassados',
              '• 1 pacote de queijo ralado'],
            },
          ],

        }
    
    },

    {
        id: '2',
        nome: 'Strogonoff de frango',
        img: img_strogonoff, 
        nota: '4.9',
        tempo: '20min',
        dificuldade: 'Fácil',
        preparo: { 
            sections: [
            {
              title: 'Modo de Preparo',
              data: [
                '1 - Tempere o frango em cubos com sal e a maionese.',
                '',
                '2 - Em uma frigideira grande adicione o azeite.',
                '',
                '3 - Doure a cebola e o alho.',
                '',
                '4 - Adicione o frango temperado e deixe dourando.',
                '',
                '5 - Adicione os cogumelos, a mostarda e em seguida o ketchup.',
                '',
                '6 - Acrescente o creme de leite e mexa bem.',
                '',
                '7 - Faça as correções do sal se achar necessário.',
                '',
                '8 - Sirva com arroz branco e batata palha.',
              ],
            },
            ],
        },
        ingredientes: { sections: [
            {
              title: 'Ingredientes (5 porções)',
              data: ['• 500 g de peito de frango cortado em cubos',
              '• 1 cebola picada',
              '• 1 dente de alho picado',
              '• sal ',
              '• 1 colher de azeite',
              '• 2 colheres (sopa) de maionese',
              '• 1 colher (sopa) de mostarda',
              '• 1 copo ou sachê de cogumelos a gosto',
              '• 1 caixa de creme de leite',
              '• batata palha a gosto'],
            },
          ],

        }
    },
     {
        id: '3',
        nome: 'Pavê de chocolate', 
        img: img_pave, 
        nota: '4.8',
        tempo: '35min',
        dificuldade: 'Fácil',
        preparo: { 
            sections: [
            {
              title: 'Modo de Preparo',
              data: [
                'Preparo do creme:',
                '',
                '1 - Numa panela adicione os 400ml leite, a Maizena (amido de milho), o leite condensado, a gema, o creme de leite e a essência de baunilha.',
                '',
                '2 - Misture e leve ao fogo médio, mexendo sem parar.',
                '',
                '3 - Mexa até engrossar e começar a soltar do fundo da panela.',
                '',
                '4 - Restire do fogo, transfira para uma tigela e aguarde esse creme esfriar completamente. Reserve.',
                '',
                '5 - Em uma forma ou travessa de vidro faça uma camada com o creme ja frio.',
                '',
                '6 - Mergulhe as bolachas Maizena no leite, rapidamente para não encharcar.',
                '',
                '7 - Em seguida vá acomodando as bolachas na travessa, deixando uma do lado da outra, formando uma camada.',
                '',
                '8 - Faça uma camada de creme por cima dessa bolachas.',
                '',
                '9 - Continue fazendo esse processo até terminar com o creme por cima de tudo, em seguida leve para geladeira por 2 horas.',
                '',
                'Preparo do  ganache:',
                '',
                '1 - Numa panela, despeje o creme de leite e leve ao fogo médio.',
                '',
                '2 - Quando começar a levantar fervura, desligue o fogo imediatamente.',
                '',
                '3 - Adicione o chocolate ao leite ou de sua preferência e mexa até derreter completamente e formar um ganache.',
                '',
                '4 - Aguarde esfriar e despeje esse ganache por cima da ultima camada de creme e espalhe bem.',
                '',
                '5 - Leve para a geladeira, deixe por 3 horas e seja feliz!',
                
              ],
            },
            ],
        },
        ingredientes: { sections: [
            {
              title: 'Ingredientes (8 porções)',
              data: [' Creme:',
              '• 400 ml de leite',
              '• 1 colher de (sopa) de amido de milho (maizena)',
              '• 1 caixa de leite condensado',
              '• 1 unidade de gema',
              '• 1 caixa de creme de leite',
              '• 1 colher de (chá) de essência de baunilha',
              '• 2 pacotes de bolacha maizena ou champanhe (vai do sua preferência)',
              '• 1/2 xícara de (chá) de leite (para umedecer as bolachas)',
              '',
              ' Ganache:',
              '• 1 caixa de creme de leite',
              '• 1 barra de chocolate ao leite (ou de sua preferência)',
              ],
            },
          ],

        }
    },
     {
        id: '4', 
        nome: 'Coxinha de frango', 
        img: img_coxinha, 
        nota: '4.8',
        tempo: '50 minutos',
        dificuldade: 'Média',
        preparo: { 
          sections: [
          {
            title: 'Modo de Preparo',
            data: [
              'Preparo do creme:',
              '',
              '1 - Numa panela adicione os 400ml leite, a Maizena (amido de milho), o leite condensado, a gema, o creme de leite e a essência de baunilha.',
              '',
              '2 - Misture e leve ao fogo médio, mexendo sem parar.',
              '',
              '3 - Mexa até engrossar e começar a soltar do fundo da panela.',
              '',
              '4 - Restire do fogo, transfira para uma tigela e aguarde esse creme esfriar completamente. Reserve.',
              '',
              '5 - Em uma forma ou travessa de vidro faça uma camada com o creme ja frio.',
              '',
              '6 - Mergulhe as bolachas Maizena no leite, rapidamente para não encharcar.',
              '',
              '7 - Em seguida vá acomodando as bolachas na travessa, deixando uma do lado da outra, formando uma camada.',
              '',
              '8 - Faça uma camada de creme por cima dessa bolachas.',
              '',
              '9 - Continue fazendo esse processo até terminar com o creme por cima de tudo, em seguida leve para geladeira por 2 horas.',
              '',
              'Preparo do  ganache:',
              '',
              '1 - Numa panela, despeje o creme de leite e leve ao fogo médio.',
              '',
              '2 - Quando começar a levantar fervura, desligue o fogo imediatamente.',
              '',
              '3 - Adicione o chocolate ao leite ou de sua preferência e mexa até derreter completamente e formar um ganache.',
              '',
              '4 - Aguarde esfriar e despeje esse ganache por cima da ultima camada de creme e espalhe bem.',
              '',
              '5 - Leve para a geladeira, deixe por 3 horas e seja feliz!',
              
            ],
          },
          ],
      },
      ingredientes: { sections: [
          {
            title: 'Ingredientes (8 porções)',
            data: [' Creme:',
            '• 400 ml de leite',
            '• 1 colher de (sopa) de amido de milho (maizena)',
            '• 1 caixa de leite condensado',
            '• 1 unidade de gema',
            '• 1 caixa de creme de leite',
            '• 1 colher de (chá) de essência de baunilha',
            '• 2 pacotes de bolacha maizena ou champanhe (vai do sua preferência)',
            '• 1/2 xícara de (chá) de leite (para umedecer as bolachas)',
            '',
            ' Ganache:',
            '• 1 caixa de creme de leite',
            '• 1 barra de chocolate ao leite (ou de sua preferência)',
            ],
          },
        ],

      }
    },
     {
        id: '5', 
        nome: 'Cookies Americano', 
        img: img_cookie,
        nota: '4.8',
        tempo: '50 minutos',
        dificuldade: 'Média',
        preparo: { 
          sections: [
          {
            title: 'Modo de Preparo',
            data: [
              'Preparo do creme:',
              '',
              '1 - Numa panela adicione os 400ml leite, a Maizena (amido de milho), o leite condensado, a gema, o creme de leite e a essência de baunilha.',
              '',
              '2 - Misture e leve ao fogo médio, mexendo sem parar.',
              '',
              '3 - Mexa até engrossar e começar a soltar do fundo da panela.',
              '',
              '4 - Restire do fogo, transfira para uma tigela e aguarde esse creme esfriar completamente. Reserve.',
              '',
              '5 - Em uma forma ou travessa de vidro faça uma camada com o creme ja frio.',
              '',
              '6 - Mergulhe as bolachas Maizena no leite, rapidamente para não encharcar.',
              '',
              '7 - Em seguida vá acomodando as bolachas na travessa, deixando uma do lado da outra, formando uma camada.',
              '',
              '8 - Faça uma camada de creme por cima dessa bolachas.',
              '',
              '9 - Continue fazendo esse processo até terminar com o creme por cima de tudo, em seguida leve para geladeira por 2 horas.',
              '',
              'Preparo do  ganache:',
              '',
              '1 - Numa panela, despeje o creme de leite e leve ao fogo médio.',
              '',
              '2 - Quando começar a levantar fervura, desligue o fogo imediatamente.',
              '',
              '3 - Adicione o chocolate ao leite ou de sua preferência e mexa até derreter completamente e formar um ganache.',
              '',
              '4 - Aguarde esfriar e despeje esse ganache por cima da ultima camada de creme e espalhe bem.',
              '',
              '5 - Leve para a geladeira, deixe por 3 horas e seja feliz!',
              
            ],
          },
          ],
      },
      ingredientes: { sections: [
          {
            title: 'Ingredientes (8 porções)',
            data: [' Creme:',
            '• 400 ml de leite',
            '• 1 colher de (sopa) de amido de milho (maizena)',
            '• 1 caixa de leite condensado',
            '• 1 unidade de gema',
            '• 1 caixa de creme de leite',
            '• 1 colher de (chá) de essência de baunilha',
            '• 2 pacotes de bolacha maizena ou champanhe (vai do sua preferência)',
            '• 1/2 xícara de (chá) de leite (para umedecer as bolachas)',
            '',
            ' Ganache:',
            '• 1 caixa de creme de leite',
            '• 1 barra de chocolate ao leite (ou de sua preferência)',
            ],
          },
        ],

      }
    },
     {
        id: '6', 
        nome: 'Hambúrguer Caseiro', 
        img: img_hamburguer, 
        nota: '4.8',
        tempo: '50 minutos',
        dificuldade: 'Média',
        preparo: { 
          sections: [
          {
            title: 'Modo de Preparo',
            data: [
              'Preparo do creme:',
              '',
              '1 - Numa panela adicione os 400ml leite, a Maizena (amido de milho), o leite condensado, a gema, o creme de leite e a essência de baunilha.',
              '',
              '2 - Misture e leve ao fogo médio, mexendo sem parar.',
              '',
              '3 - Mexa até engrossar e começar a soltar do fundo da panela.',
              '',
              '4 - Restire do fogo, transfira para uma tigela e aguarde esse creme esfriar completamente. Reserve.',
              '',
              '5 - Em uma forma ou travessa de vidro faça uma camada com o creme ja frio.',
              '',
              '6 - Mergulhe as bolachas Maizena no leite, rapidamente para não encharcar.',
              '',
              '7 - Em seguida vá acomodando as bolachas na travessa, deixando uma do lado da outra, formando uma camada.',
              '',
              '8 - Faça uma camada de creme por cima dessa bolachas.',
              '',
              '9 - Continue fazendo esse processo até terminar com o creme por cima de tudo, em seguida leve para geladeira por 2 horas.',
              '',
              'Preparo do  ganache:',
              '',
              '1 - Numa panela, despeje o creme de leite e leve ao fogo médio.',
              '',
              '2 - Quando começar a levantar fervura, desligue o fogo imediatamente.',
              '',
              '3 - Adicione o chocolate ao leite ou de sua preferência e mexa até derreter completamente e formar um ganache.',
              '',
              '4 - Aguarde esfriar e despeje esse ganache por cima da ultima camada de creme e espalhe bem.',
              '',
              '5 - Leve para a geladeira, deixe por 3 horas e seja feliz!',
              
            ],
          },
          ],
      },
      ingredientes: { sections: [
          {
            title: 'Ingredientes (8 porções)',
            data: [' Creme:',
            '• 400 ml de leite',
            '• 1 colher de (sopa) de amido de milho (maizena)',
            '• 1 caixa de leite condensado',
            '• 1 unidade de gema',
            '• 1 caixa de creme de leite',
            '• 1 colher de (chá) de essência de baunilha',
            '• 2 pacotes de bolacha maizena ou champanhe (vai do sua preferência)',
            '• 1/2 xícara de (chá) de leite (para umedecer as bolachas)',
            '',
            ' Ganache:',
            '• 1 caixa de creme de leite',
            '• 1 barra de chocolate ao leite (ou de sua preferência)',
            ],
          },
        ],

      }
    },
]

export default especiais;